### ISSUE TITLE
Add a `compiled_module` API for eager-mode compilation

### ISSUE THREAD

**Issue by Chillee** [facebookresearch/functorch#109]
The current `compiled_function` API only works with functions - it can't be applied to modules directly. It would be good to provide a wrapper that wraps the forward function to pull out the parameters and pass them in.

For example
```
class Foo(nn.Module):
    def __init__(self):
        self.param = nn.Parameter(torch.randn(3))
    
    def forward(self, x):
        return x * self.param

def functionalized(x, param):
    return x * param
   
functionalized = compiled_function(functionalized) 
class Foo(nn.Module):
    def __init__(self):
        self.param = nn.Parameter(torch.randn(3))
         
    def forward(self, x):
        return functionalized(x, self.param)
```

This PR for Cuda Graphs can serve as an example of how to do it: https://github.com/pytorch/pytorch/pull/63269/files#diff-39e542d87359e7d5381d036cbcea9ec759fbe469578bcdc5693ce6cfab7f1a54

**Comment by Chillee** [comment]
@huiguoo

**Comment by zou3519** [comment]
From offline discussion with Chillee:

One approach is to use `make_functional` for this. `compiled_module(mod)(inputs)` would probably
- use make_functional on the mod, returning (parameters, functional_mod)
- the trace the forward and backward of functional_mod(parameters, inputs)
- The forward pass that gets compiled accepts (parameters, inputs). The forward+backward pass get stitched together in an autograd.Function (call this CompiledFunction)
- So compiled_module would return a new nn.Module that has the same parameters whose forward pass invokes CompiledFunction

**Comment by Chillee** [comment]
Closed by https://github.com/facebookresearch/functorch/pull/133
