### ISSUE TITLE
`argnum` to select `jacrev` differentiation argument

### ISSUE THREAD

**Issue by Zymrael** [facebookresearch/functorch#110]
Any plans to add `argnum` to `jacrev` -- similarly to [JAX ](https://jax.readthedocs.io/en/latest/jax.html?highlight=jacrev#jax.jacrev)-- for supporting functions with multiple arguments? 

An example use case I'm looking at is: `vmap(jacrev(f, argnums=0), in_dims=(0, 0))(x1, x2)`

**Comment by Chillee** [comment]
Yeah, it shouldn't be that hard to add. I'll take a crack at it after running some errands :P

**Comment by Chillee** [comment]
@samdow just added it in a PR, could @Zymrael  confirm that it works for your use case?

**Comment by Zymrael** [comment]
@Chillee works great, thanks!
