### ISSUE TITLE
Better testing plan for batching rule of backward ops

### ISSUE THREAD

**Issue by zou3519** [facebookresearch/functorch#28]
There's not a methodological way to test the batching rule backward op right now through all of the edge cases

**Comment by Chillee** [comment]
hmmmm..... does testing grad + our current opinfo vmap tests suffice?

**Comment by zou3519** [comment]
I'm working on this. I'll probably add testing for all pairs of { vmap, vjp, None} x { vmap, vjp } (grad is really just a special case of vjp, but we didn't implement it like that, so maybe grad needs to go in there too).

This design is not the greatest because it implies that if we have N transforms then each OpInfo test will generate N ** 2 tests which seem bad for runtime. Maybe in the future we'll decide to test fewer pairs when we have more confidence in the dynamic layering mechanism or add some "structure" to our transforms to make it so that it's impossible for them to not compose.
