### ISSUE TITLE
__torch_function__ resolution order is not implemented correctly

### ISSUE THREAD

**Issue by ezyang** [facebookresearch/functorch#39]
https://github.com/zou3519/functorch/blob/68df44f7cdb72864d5e43674357bca7a57b81220/functorch/csrc/PythonKey.cpp#L121

It's not sufficient to only look at the first tensor argument. The correct algorithm is described at https://github.com/pytorch/rfcs/blob/master/RFC-0001-torch-function-for-methods.md#process-followed-during-a-functionmethod-call

**Comment by zou3519** [comment]
Fixed via @Chillee migrating to new Python key
