### ISSUE TITLE
Use vmap on functions with if-statements

### ISSUE THREAD

**Issue by YPWotte** [facebookresearch/functorch#90]
This is my minimal example that causes a RunTime Error:

```python
import torch
from functorch import vamp 
def test(th):
    if th > 0:
        return 1/th
    else:
        return th
vmap(test)(torch.randn(2))
```
The error is
```
*** RuntimeError: Batching rule not implemented for aten::is_nonzero. We could not generate a fallback.
```

It seems to be the if-statement that gives trouble. In my original code, i need to use such if-statements to guarantee numerical accuracy of some otherwise ill-conditioned functions, so really there seems to be no way around using them. Are there any plans to implement support for this? 

Best regards,
Yannik

**Comment by zou3519** [comment]
@YPWotte the current thinking is that we are going to investigate adding a `functorch.if(input, true_fn, false_fn)` operator that can be vmap'ed over. This would require the user to rewrite code that uses python `if` to using the control flow operator.

**Comment by Chillee** [comment]
@YPWotte 

One thing you can do is rewrite your code with `where` statements.

In your example, there's an additional problem in that you're comparing a tensor with an integer, which might not be what you want?

```
def f(x):
    return torch.where(th > 0, 1/th, th)
```

**Comment by YPWotte** [comment]
@zou3519 that sounds great! For now i will follow @Chillee 's advice, it seems like that could be sufficient for my code. Thanks a lot!
